version: "2"
services:
    app:
        image: "node:12"
        user: "node"
        working_dir: "/home/node/app"
        environment: 
            - NODE_ENV=production
        volumes: 
            - ./server-api-node:/home/node/app
            # - ./client-angular/dist/highlightsCSGO:/home/node/app/dist
        ports:
          - "82:3000"
        command: npm run 
