version: "3"
services:
    app:
        build: 
            context: .            
        user: "node"
        working_dir: "/home/node/app"
        environment: 
            - NODE_ENV=production
        ports:
          - "82:3000"
